config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: :show do
    resources :profiles, only: [:new, :create, :edit ,:update] 
  end 

  resources :posts do
    post 'add' => 'goods#create'
    delete '/add' => 'goods#destroy'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :motivate_credentials
  has_many :posts
  has_many :comments
  has_many :goods, dependent: :destroy
  has_many :good_posts, through: :goods, source: :post
  has_one :profile
  has_one_attached :image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.from_omniauth(auth)
    motivate = MotivateCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    #userが登録済みであるか判断
    if user.persisted?
      motivate.user = user
      motivate.save
    end
    { user: user, motivate: motivate }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def facebook
    authorization
   end
  
   def google_oauth2
    authorization
   end
  
   private
  
   def authorization
     motivate_info = User.from_omniauth(request.env["omniauth.auth"])
     @user = motivate_info[:user]

     if @user.persisted? #ユーザー情報が登録ずみのため、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
     else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @motivate_id = motivate_info[:motivate].id
      render template: 'devise/registrations/new'
     end

   end


  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:motivate_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
     super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user = User.find(params[:id])
    @posts = user.posts
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_followings'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_followers'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
    <%#<%= render 'shared/error_messages', model: @post %>
      <%#<%= form_with model: @post, url: posts_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :"プロフィール画像" %><br />
          <%= f.file_field :"hoge"  %>
        </div>

        <div class="form-group">
          <%= f.label :"紹介文" %><br />
          <%= f.text_area :"hoge", class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "編集する", class: "btn-sm btn-dark" %>
        </div>
      <%#<% end %>
    </div>
  </div>

<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header"%>
<div class="container">
  <div class="profile-wrapper">
    <% unless @user.profile.nil? %>
      <div class="profile-image">
      <%= image_tag @user.profile.image, size: '150x150' ,class: "rounded-circle border border-secondary" %>
      </div>
    <% else %>
      <div class="profile-image" >
       <i class="fas fa-user fa-6x fa-border"></i>
      </div>
    <% end %>
      <div class="follow-btn">
        <ul class="follow-list">
       
      <% if current_user.id == @user.id %>
       <% if @user.profile.nil? %>
          <li>
            <%= link_to "プロフィール作成", new_user_profile_path(@user.id), class: "btn btn-primary btn-lg" %>
          </li>
        <% else %>
          <li>
            <%= link_to "プロフィール更新", edit_user_profile_path(@user.profile.id), class: "btn btn-primary btn-lg" %>
          </li>
        <% end %>
      <% else %>
        <li>
          <%= render "relationships/follow_button", user: @user %>
        </li>
      <% end %>
        <li>
        <%= link_to @user.followers.count, followers_user_path(@user) %><p>フォロワー</p>
        </li>
        <li>
        <%= link_to @user.followings.count, following_user_path(@user) %><p>フォロー中</p>
        </li>
      </ul>
    </div>
    <% if @user.profile.present? %>
    <div class="profile-info">
    <%= @user.profile.info %>
    </div>
    <% else %>
    <div class="profile-info">
    <p>プロフィールを更新し、ここに自己紹介を表示させてください。</p>
    </div>
    <% end %> 
  </div>
    <div class="card-wrapper">
      <% @posts.each do |post|%>
        <%= render partial: "shared/post", locals: { post: post }%>
      <% end %> 
    </div>
  
</div>


<%= render "shared/footer"%>

app/views/users/show_followers.html.erb
<%= render "shared/header"%>
  <div class="follow-wrapper">
  <h1 class="top-message">フォロワ一覧</h1>
    <% @user.followers.each do |user| %>
      <div class="follow-content">
        <% unless user.profile.nil? %>
          <div class="profile-image">
            <%= image_tag user.profile.image, size: '50x50' ,class: "rounded-circle border border-secondary" %>
          </div>
        <% else %>
        <div class="profile-image" >
          <i class="fas fa-user fa-2x fa-border"></i>
        </div>
        <% end %>
          <%= link_to user.name, user_path(user.id), class: "user-name" %>
      </div>
    <% end %>
</div>
<%= render "shared/footer"%>

app/views/users/show_followings.html.erb
<%= render "shared/header"%>
<div class="follow-wrapper">
  <h1 class="top-message">フォロ中一覧</h1>
    <% @user.followings.each do |user| %>
      <div class="follow-content">
        <% unless user.profile.nil? %>
          <div class="profile-image">
            <%= image_tag user.profile.image, size: '50x50' ,class: "rounded-circle border border-secondary" %>
          </div>
        <% else %>
        <div class="profile-image" >
          <i class="fas fa-user fa-2x fa-border"></i>
        </div>
        <% end %>
          <%= link_to user.name, user_path(user.id), class: "user-name" %>
      </div>
    <% end %>
</div>
  
<%= render "shared/footer"%>