config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: :show do
    resources :profiles, only: [:new, :create, :edit ,:update] 
  end 

  resources :posts do
    post 'add' => 'goods#create'
    delete '/add' => 'goods#destroy'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/motivate_credential.rb
class MotivateCredential < ApplicationRecord
     belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :users, through: :goods
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :goods, dependent: :destroy
  with_options presence: true do
    validates :text
    validates :image
  end

  def liked_by?(user)
    goods.where(user_id: user.id).exists?
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :motivate_credentials
  has_many :posts
  has_many :comments
  has_many :goods, dependent: :destroy
  has_many :good_posts, through: :goods, source: :post
  has_one :profile
  has_one_attached :image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.from_omniauth(auth)
    motivate = MotivateCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    #userが登録済みであるか判断
    if user.persisted?
      motivate.user = user
      motivate.save
    end
    { user: user, motivate: motivate }
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item
  def create
    user = current_user
    post = Post.find(params[:post_id])
    good = Good.create(user_id: user.id, post_id: post.id)
  end

  def destroy
    user = current_user
    post = Post.find(params[:post_id])
    good = Good.find_by(user_id: user.id, post_id: post.id)
    good.destroy
  end

private

  def set_item
    @post = Post.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
before_action :move_to_index
  def index
  end

  def move_to_index
    if user_signed_in?
      redirect_to controller: :posts, action: :index
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_item, only: [:show,  :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :move_to_index, only: [:destroy, :edit] 
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_item
    @post = Post.find(params[:id])
  end

  def move_to_index
    if current_user.id != @post.user_id
      redirect_to root_path 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user = User.find(params[:id])
    @posts = user.posts
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_followings'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_followers'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motivate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-lg-start fixed-bottom">
      <!-- Copyright -->
      <div class="text-center p-3 text-white" >
        © 2021 Copyright:
        <a class="text-white" href="#">MOTIVATE</a>
      </div>
      <!-- Copyright -->
    </footer>

app/views/shared/_header.html.erb
<nav class="header-bar navbar-dark bg-dark fixed-top">
<% if user_signed_in? %>
  <div class="header-right"><%= link_to posts_path do%>
  <%= image_tag 'logo.png' , size: '160x80'  %>
  <% end %>
  </div>
<% else %>
  <div class="header-right"><%= link_to new_user_session_path do%>
  <%= image_tag 'logo.png' , size: '160x80'  %>
  <% end %>
  </div>
<% end %>

  <div class="header-center"><% if user_signed_in? %>
  <i class="fas fa-running">：<%= link_to  current_user.name , user_path(current_user.id), class:"current_name" %></i>
<% end %></div>
 <div class="header-left"><% unless user_signed_in? %>
      <%= link_to new_user_session_path, class: "log login" do%>
        <i class="fas fa-door-open">ログイン</i>
      <% end %>
      <%= link_to  new_user_registration_path, class: "log" do%>
      <i class="fas fa-sign-in-alt">サインアップ</i>
      <% end %>
    <% else %>
      <%= link_to destroy_user_session_path, method: :delete, class:"log" do%>
      <i class="fas fa-sign-out-alt">ログアウト</i>
      <% end %>
    <% end %></div>
</nav>



 

app/views/shared/_post.html.erb
<div class ="card">
  <div class="image-body">
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.image, class: "image-size" %>
    <% end %>
  </div>
  <div class="text-body">
    
      <div class="options">
        <% if user_signed_in? %>
          <div class="like_button", id="like-btn-<%= post.id %>">
              <%= render 'goods/good', post: post %>
          </div>
        <% end %>
          <% if user_signed_in? && current_user.id == post.user_id%>
            <%= link_to "編集", edit_post_path(post.id), class:"btn-sm btn-dark"%>
            <%= link_to "削除", post_path(post.id), method: :delete, class:"btn-sm btn-dark"%>
          <% end %>
      </div>
      <%= link_to user_path(post.user.id),class: "user-name" do%>
      <i class="fas fa-running">：<%= post.user.name %></i>
      <% end %>
         <div class="message"><i class="far fa-sticky-note"></i><%= post.text %></div>
        <div class="create-time"><%= l post.created_at, format: :short %></div>
  </div>
</div>