config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: :show do
    resources :profiles, only: [:new, :create, :edit ,:update] 
  end 

  resources :posts do
    post 'add' => 'goods#create'
    delete '/add' => 'goods#destroy'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/motivate_credential.rb
class MotivateCredential < ApplicationRecord
     belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :users, through: :goods
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :goods, dependent: :destroy
  with_options presence: true do
    validates :text
    validates :image
  end

  def liked_by?(user)
    goods.where(user_id: user.id).exists?
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :motivate_credentials
  has_many :posts
  has_many :comments
  has_many :goods, dependent: :destroy
  has_many :good_posts, through: :goods, source: :post
  has_one :profile
  has_one_attached :image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.from_omniauth(auth)
    motivate = MotivateCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    #userが登録済みであるか判断
    if user.persisted?
      motivate.user = user
      motivate.save
    end
    { user: user, motivate: motivate }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    posts_path(resource)
  end

  def after_sign_up_path_for(resource)
    posts_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item, only: :destroy
  before_action :move_to_index, only: [:create, :destroy] 
  before_action :only_action, only: :destroy
  def create
    @post = Post.find(params[:post_id])
    comment = Comment.new(comment_params) 
    if comment.valid?
      comment.save
      redirect_to post_path(comment.post.id)
    else
      flash[:danger] = 'commentを入力してください'
      redirect_to  post_path(comment.post.id)
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@comment.post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_item
    @comment = Comment.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def only_action
    if current_user.id != @comment.user.id
      redirect_to root_path
    end
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item
  def create
    user = current_user
    post = Post.find(params[:post_id])
    good = Good.create(user_id: user.id, post_id: post.id)
  end

  def destroy
    user = current_user
    post = Post.find(params[:post_id])
    good = Good.find_by(user_id: user.id, post_id: post.id)
    good.destroy
  end

private

  def set_item
    @post = Post.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
before_action :move_to_index
  def index
  end

  def move_to_index
    if user_signed_in?
      redirect_to controller: :posts, action: :index
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_item, only: [:show,  :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :move_to_index, only: [:destroy, :edit] 
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_item
    @post = Post.find(params[:id])
  end

  def move_to_index
    if current_user.id != @post.user_id
      redirect_to root_path 
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index,  only: :edit
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create(profile_params)
    redirect_to user_path(@profile.user.id)
  end
  

  def edit 
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    redirect_to user_path(@profile.user.id)
  end

  private

  def profile_params
    params.require(:profile).permit(:info, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    if current_user.id != current_user.id
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user = User.find(params[:id])
    @posts = user.posts
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_followings'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_followers'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goods/_good.html.erb
  <% if post.liked_by?(current_user) %>
    <%= link_to  post_add_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}" do%>
      <i class="fas fa-dumbbell fa-lg size" alt="good" ></i>
    <% end %>
    <%= image_tag "motivate.jpeg", size: "90x100", class: "good-image", id: "good-img" %>
  <% else %>
    <%= link_to  post_add_path(post), method: :post, remote: true, id: :"like-button-#{post.id}" do%>
      <i class="fas fa-dumbbell fa-lg formal" alt="good" ></i>
    <% end %>
    
  <% end %>

app/views/goods/create.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "goods/good", locals: { post: @post }) %>");

app/views/goods/destroy.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "goods/good", locals: { post: @post }) %>");

app/views/posts/edit.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
    <%= render 'shared/error_messages', model: @post %>
      <%= form_with model: @post,url: post_path,local: true do |f| %>
        <div class="form-group">
          <%= f.label :"画像" %><br />
          <%= f.file_field :image  %>
        </div>
        <div id="image-list">Preview:</div>
        <div class="form-group">
          <%= f.label :"文章" %><br />
          <%= f.text_area :text, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "編集する", class: "btn-sm btn-dark" %>
        </div>
      <% end %>
    </div>
  </div>

<%= render "shared/footer"%>

app/views/posts/index.html.erb
<%= render "shared/header"%>

<%# 投稿一覧%>
<div class="container">
    <div class="card-wrapper row">
      <% @posts.each do |post|%>
        <%= render partial: "shared/post", locals: { post: post }%>
      <% end %>
      <% unless @posts.present? %>
        <div class ="card">
          <div class="image-body">
            <%= link_to "#" do %>
              <%= image_tag 'sample.jpg', class: "image-size" %>
            <% end %>
          </div>
          <div class="text-body">
            <div class="options">
              <i class="fas fa-dumbbell fa-lg formal"></i>
              <%= link_to "編集", '#', class:"btn-sm btn-dark"%>
              <%= link_to "削除", '#', class:"btn-sm btn-dark"%>
            </div>
            <%= link_to "#", class: "user-name" do%>
              <i class="fas fa-running">：鍛えた体をシェアする</i>
            <% end %>
           <div class="message"><i class="far fa-sticky-note"></i>日々のトレーニングで鍛えた体をシェア。<br>モチベーションになったらダンベルのマークを押してあげよう！</div>
           <div class="create-time">21/12:00</div>
          </div>
        </div>
        <div class ="card">
          <div class="image-body">
            <%= link_to "#" do %>
              <%= image_tag 'sample3.jpg', class: "image-size" %>
            <% end %>
          </div>
          <div class="text-body">
            <div class="options">
              <i class="fas fa-dumbbell fa-lg formal"></i>
              <%= link_to "編集", '#', class:"btn-sm btn-dark"%>
              <%= link_to "削除", '#', class:"btn-sm btn-dark"%>
            </div>
            <%= link_to "#", class: "user-name" do%>
              <i class="fas fa-running">：食事をシェアする</i>
            <% end %>
           <div class="message"><i class="far fa-sticky-note"></i>体をつくった食事をシェア。<br>モチベーションになったらダンベルのマークを押してあげよう！</div>
           <div class="create-time">21/12:00</div>
          </div>
        </div>
        <div class ="card">
          <div class="image-body">
            <%= link_to "#" do %>
              <%= image_tag 'sample2.jpg', class: "image-size" %>
            <% end %>
          </div>
          <div class="text-body">
            <div class="options">
              <i class="fas fa-dumbbell fa-lg formal"></i>
              <%= link_to "編集", '#', class:"btn-sm btn-dark"%>
              <%= link_to "削除", '#', class:"btn-sm btn-dark"%>
            </div>
            <%= link_to "#", class: "user-name" do%>
              <i class="fas fa-running">：ライフスタイルをシェアする</i>
            <% end %>
           <div class="message"><i class="far fa-sticky-note"></i>イけてるライフスタイルをシェア。<br>モチベーションになったらダンベルのマークを押してあげよう！</div>
           <div class="create-time">21/12:00</div>
          </div>
        </div>
     <% end %>
    </div>
  <% if user_signed_in? %>
    <%= link_to(new_post_path, class: 'post-btn') do %>
    <span class='post-btn-text'>投稿する</span>
    <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "post-btn-icon" %>
  <% end %>
<% end %>
</div>



<%= render "shared/footer"%>

app/views/posts/new.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
    <%= render 'shared/error_messages', model: @post %>
      <%= form_with model: @post, url: posts_path, local: true do |f| %>
      
        <div class="form-group">
          <%= f.label :"画像" %><br />
          <%= f.file_field :image  %>
        </div>
        <div id="image-list">Preview:</div>

        <div class="form-group">
          <%= f.label :"文章" %><br />
          <%= f.text_area :text, class: "form-control" %>
        </div>


        <div class="actions">
          <%= f.submit "投稿する", class: "btn-sm btn-dark" %>
        </div>
        
      <% end %>
    </div>
  </div>

<%= render "shared/footer"%>

app/views/posts/show.html.erb
<%= render "shared/header"%>
<div class="container">
  <div class="detail-wrapper">
      <div class ="detail-card">
        <div class="image-body">
          <%= image_tag @post.image, class: "image-size" %>
        </div>
        <div class="text-body">
        <div class="options">
          <% if user_signed_in? %>
            <div class="like_button", id="like-btn-<%= @post.id %>">
              <%= render 'goods/good', post: @post %>
          </div>
          <% end %>
            <% if user_signed_in? && current_user.id == @post.user_id%>
              <%= link_to "編集", edit_post_path(@post.id), class:"btn-sm btn-dark"%>
              <%= link_to "削除", post_path(@post.id), method: :delete, class:"btn-sm btn-dark"%>
            <% end %>
        </div>
            <%= link_to user_path(@post.user.id),class: "user-name" do%>
              <i class="fas fa-running">：<%= @post.user.name %></i>
            <% end %>
        <div class="detail-message"><i class="far fa-sticky-note"></i><%= @post.text %></div>
        <div class="create-time"><%= l @post.created_at, format: :short %></div>
      </div>
  </div>
  <div class="comment-wrapper">
        <%= form_with model: [@post,@comment], local: true do |f| %>
          <% if flash[:danger] %>
        <div class="error-messages">
          <%= flash[:danger] %>
        </div>
        <% end %>
          <div class="form-group">
            <%= f.label :"コメント" %><br />
            <%= f.text_area :comment, class: "form-control" %>
          </div>
          <div class="actions">
            <%= f.submit "コメントする", class: "btn-sm btn-dark" %>
          </div>
        <% end %>
        <div class="comments">
        <% @comments.each do |comment| %>
          <div class="comment">
            <%= link_to comment.user.name, user_path(@post.user.id), class: "user-name"%>
            <% if current_user.id == comment.user.id %>
            <%= link_to "削除", post_comment_path(@post.id, comment.id), method: :delete, class:"btn-sm btn-dark py-0"%>
            <% end %>
            <p><%= comment.comment%><p>
          </div>
        <% end %>
      </div>
</div>


<%= render "shared/footer" %>

app/views/profiles/edit.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
      <%= form_with model: @profile,url: user_profile_path, local: true do |f| %>
          <div class="form-group">
            <%= f.label :"プロフィール画像" %><br />
            <%= f.file_field :image  %>
          </div>

          <div class="form-group">
            <%= f.label :"紹介文" %><br />
            <%= f.text_area :info, class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit "編集する", class: "btn-sm btn-dark" %>
          </div>
      <% end %>
    </div>
  </div>

<%= render "shared/footer"%>

app/views/profiles/index.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
    <%#<%= render 'shared/error_messages', model: @post %>
      <%= form_with (model: @user_profile, url: users_path, local: true) do |f| %>
          <div class="form-group">
            <%= f.label :"プロフィール画像" %><br />
            <%= f.file_field :image  %>
          </div>

          <div class="form-group">
            <%= f.label :"紹介文" %><br />
            <%= f.text_area :info, class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit "編集する", class: "btn-sm btn-dark" %>
          </div>
      <% end %>
    </div>
  </div>

<%= render "shared/footer"%>

app/views/profiles/new.html.erb
<%= render "shared/header"%>
    
  <div class="container">
    <div class="form-wrapper">
      <%= form_with model: @profile, url: user_profiles_path, local: true do |f| %>
          <div class="form-group">
            <%= f.label :"プロフィール画像" %><br />
            <%= f.file_field :image  %>
          </div>

          <div class="form-group">
            <%= f.label :"紹介文" %><br />
            <%= f.text_area :info, class: "form-control" %>
          </div>

          <div class="actions">
            <%= f.submit "編集する", class: "btn-sm btn-dark" %>
          </div>
      <% end %>
    </div>
  </div>

<%= render "shared/footer"%>